#Pixel coordinates
int32 x
int32 y
#Approach angle
float64 theta 

#Types
int32 OTHER=0
int32 HEEL=1
int32 TOE=2
int32 OPENING=3
#Special Bunched Features
int32 BUNCH_SEAM=4
int32 BUNCH_INSIDE_OUT=5
int32 mode

bool use_nearest
int32 type
string model_file
---
float64 response
